/* Copyright (c) 2026 VillageSQL Contributors
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef VILLAGESQL_SQL_CUSTOM_VDF_H_
#define VILLAGESQL_SQL_CUSTOM_VDF_H_

#include <sys/types.h>
#include <string>

#include "lex_string.h"
#include "my_inttypes.h"

class Query_tables_list;
class Query_arena;

template <typename T>
class SQL_I_List;

// Represents an element in the set of custom routines (extension VDFs)
// used by a statement.
// Analogous to Sroutine_hash_entry, but simpler because custom VDFs
// use a straightforward key format: "extension.function".
class Croutine_hash_entry {
 public:
  // Key identifying custom routine.
  // Format: "extension.function" (as generated by make_udf_key)
  char *m_key;
  uint16 m_key_length;

  // Extension name component extracted from key
  LEX_CSTRING m_extension_name;

  // Function name component extracted from key
  LEX_CSTRING m_function_name;

  // Next element in list linking all custom routines in set.
  Croutine_hash_entry *next;
};

//  Structure for storing custom routine information with std::string.
//  Used for processing and validation after parsing.
struct Croutine_entry {
  std::string extension_name;
  std::string function_name;

  Croutine_entry(std::string &&ext, std::string &&func)
      : extension_name(std::move(ext)), function_name(std::move(func)) {}
};

// Add custom routine (extension VDF) which is used by statement to the
// set of custom routines used by this statement.
//
// @param prelocking_ctx  Prelocking context of the statement
// @param arena           Arena in which memory for new element will be
// allocated
// @param extension       Extension name
// @param ext_length      Extension name length
// @param function        Function name
// @param func_length     Function name length
//
// @note
//   Will also add element to end of 'Query_tables_list::croutines_list' list.
//
// @retval true   New element was added.
// @retval false  Element was not added (because it is already present in the
//                set).
bool custom_add_used_routine(Query_tables_list *prelocking_ctx,
                             Query_arena *arena, const char *extension,
                             size_t ext_length, const char *function,
                             size_t func_length);

#endif  // VILLAGESQL_SQL_CUSTOM_VDF_H_
